### PR TITLE
current state of manuals

### PR DESCRIPTION
**Pull request by brianharvey**
5.0 is not ready!!  Especially the two undocumented libraries on page
87.  But the whole thing needs to be indexed again.

### CODE REVIEW

**Comment by jmoenig** [comment]
Okay, thanks! So, I shouldn't be pulling this until it's done, right?

**Comment by brianharvey** [comment]
Right!  This is my first priority; it should be done soon.

**Comment by jmoenig** [comment]
Thanks for the clarification. Yes, the sooner the better, but still: No rush! The manual is already in pretty good shape and you've got plenty of stuff to handle with the lawyers this week.

**Comment by jmoenig** [comment]
bumping this thread. @brianharvey should I now pull this or wait some more? Thanks!

**Comment by jmoenig** [comment]
Thank you, @brianharvey ! Now reading...

**Comment by jmoenig** [comment]
I sent you - only - two very minor quibbles. This is looking GREAT!

**Pull request merged**
