### PR TITLE
Add download for source and libraries

### PR DESCRIPTION
**Pull request by gdavid04**
Added view source on GitHub and download source and libraries from GitHub buttons.

### CODE REVIEW

**Comment by cycomachead** [comment]
IMO, we should go from 3 links in the menu to one that points here:
https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/releases/latest

The zip file linked there will always be the version the user is using, and subsequently allows people to get to GitHub, if they desire.

**Comment by jmoenig** [comment]
Can you check whether this suggestion has now been implemented in a way that makes sense to you? Thanks!

**Comment by brianharvey** [comment]
I vote no on removing the links to the manual and the website!  Many people who feel the same way I do about git will nevertheless want to read the manual.  And the link to the website will be super important once the social site is up.

Speaking of which, when it _is_ up, I propose keeping the existing page as a sort of super-about linked to from the About box ("Click for more information").

**Comment by cycomachead** [comment]
No one was suggesting removing the links to website of manual (by 3 links, I meant that this PR adds 2 more that point to GitHub.)

Jens recent change addresses the issue, I think.

**Comment by cycomachead** [comment]
Thanks for the pull request, gdavid04, but if you feel like there's something else we can do to make finding the repo easier, let us know!

**Pull request closed without merging**
