### PR TITLE
Added Tamil Translation

### PR DESCRIPTION
**Pull request by Barthdry**
Most words that remain in english has been cleared and made into tamil. The Language translation was improved.

### CODE REVIEW

**Comment by jmoenig** [comment]
hmm... the current Tamil translation is indeed very incomplete, but so is this one. There are quite a few "mixed" strings that don't look like they are complete or intentional. Is this still a work in progress or do you actually want us to pull this now? Thank you!

**Comment by Barthdry** [comment]
You can pull this

**Comment by Barthdry** [comment]
Yes you can merge and the thing is that maybe there is no word for absolute and some maths thing.

**Comment by jmoenig** [comment]
Okay, I'm going to pull this one and reject the other one. Thank you!

**Pull request merged**
