### PR TITLE
Update lang-ru

### PR DESCRIPTION
**Pull request by temaps**

### CODE REVIEW

**Comment by jmoenig** [comment]
Ah, interesting! Your PR would allow help files to be translated, also, right? By pulling this we could also let everybody else translate help screens to their language, because they would each be in separate directories. Let me look at this more closely...

**Comment by temaps** [comment]
Yes! Just put the pictures transfer to the folder with the language ID. For the Russian folder "ru" for German, the folder "de". If the picture is not translated, it will automatically load the English picture of a folder "help"
`tmpimg.onload = function(){pic.src = ide.resourceURL('help'+'/'+SnapTranslator.language, spec + '.png');};
+        tmpimg.onerror = function(){pic.src = ide.resourceURL('help', spec + '.png');};`

**Comment by jmoenig** [comment]
I've tried to integrate your translation additions in 13d4ac87fd1575266b2530dcc16685c2534955fe, keeping your proposed little changes to the translation system open for the moment...

**Comment by temaps** [comment]
Thank You! :-)

**Pull request closed without merging**
