### PR TITLE
Fixing dropdown tranlation

### PR DESCRIPTION
**Pull request by jguille2**
Hi Jens!

You know, #2518 comments...

It's a proposal to fix the dropdown menus and the translation behavior, using your new param (verbatim) and avoiding all those changes on values (those _[name, false]_ arrays)

I've also added four new strings to Catalan locale.

Feel free to do what was better (I can resend Catalan changes)

As I said, the most changes are undoing latest changes, and the final code is more similar to yesterday code: only the new _verbatim_ param in _morphic-addItem_ and its use inside _blocks-dropdown creation_.

Joan

### CODE REVIEW

**Comment by jmoenig** [comment]
Thank you, Joan. I'll have a close look!

**Comment by jmoenig** [comment]
at first sight this looks really, nice! I didn't see you reverting my changes to ```byob.js```, though. Surely we don't want those, either, right?

**Comment by jguille2** [comment]
Hi Jens,
I've added a fix for submenus translation (current behavior neither work fine with them).
I look at _byob.js_ changes and recheck also everything.

Joan

**Comment by jmoenig** [comment]
Thank you, Joan. As I've said, I like your way a lot, it's really what I was trying to accomplish yesterday and it doesn't need the kludge of introducing yet another marker (the two-item array). So, once you've got it all together I'll gladly pull all of this!
This might take me a few days, because for the rest of the week we're pretty busy with workshops again, until Monday. So, if I find the time I'll do it in between my activities, otherwise please don't be discouraged, I *will* pull this when I find the time. Thank you!

**Comment by jguille2** [comment]
I've checket it.
Yes, these last two commits ([this](https://github.com/jmoenig/Snap/commit/9882d3dad724b79461bd95ed3cd71858398ea5ed) and [this](https://github.com/jmoenig/Snap/commit/1b5846992b1969bb6a770e420ce41a11e18fdc96)) are done after my PR.

So, if you want my proposal and you don't revert anything, we must clean these (on _byob.js_ and on _blocks.js_)

Also, if you want this line, I recheck everything to avoid more issues.

Continue...

**Comment by jguille2** [comment]
Hi Jens,
Now this proposal is directly mergeable (undoing other changes made on master tree).

I will check thoroughly all these changes to avoid new surprises. Surely I will find a case not considered in any of the two proposals.

I will post here to confirm after checking.

Joan

**Comment by jguille2** [comment]
Hi @jmoenig ,

Only posting that I have already done all my tests.

This PR is fine and ready to merge. All translatable and untranslatable strings are right.

I won't add more commits here.

Thanks,

Joan

**Comment by jmoenig** [comment]
Thank you, Joan! Will pull as soon as I find the time, probably on Tuesday.

**Pull request merged**
