### PR TITLE
JSCompiler stuff #2

### PR DESCRIPTION
**Pull request by xBZZZZ**
note: I was testing using secret cb block

1. untitled script pic now works
2. parameters now default to empty string
3. script variables now work
sv
note: JSCompiler declares variable when it compiles svv block but snap declares variable when svv block is executed:
e
4. se and c now work with script variables and parameters
note: compiled c block that changes script variable or parameter doesn't error when changing by not number
5. bypass calling `Process.prototype.reportNewList` and `Process.prototype.reportBoolean`

offtopic: why is `threads.js` formatted using both tabs and spaces?

### CODE REVIEW

**Comment by jmoenig** [comment]
thank you, this all looks great to me, I'll pull it shortly!
Hehe, many people contribute to the repo, probably using different whitespace setting in their editors. Even on my different computers and OSes there are probably different settings for that.
Thank you for this really nice and very thoughtful work! The hidden "compile" block's purpose is exactly for this, to use it for debugging the JIT compiler. I appreciate your help.

**Comment by jmoenig** [comment]
I'm sorry, I merged this and then was getting a bunch of errors, hence I've reverted it for now. Need to investigate into those errors. Hmm... can I reopen this somehow?

**Comment by xBZZZZ** [comment]
> I merged this and then was getting a bunch of errors

Send screenshot of script than gives errors.

**Comment by jmoenig** [comment]
okay, I'm adding your changes now, and then I'll try to edit some issues. Thanks!

**Comment by jmoenig** [comment]
I've pulled it and added some slight changes, mostly to appeal to JSHint's quibbles. I'd appreciate if you could look over my changes and let me know if they break anything (I hope not). Thanks!

**Pull request merged**
