### PR TITLE
Dropdown library addition

### PR DESCRIPTION
**Pull request by bruh-9000**
Create a clickable dropdown menu which runs a broadcast with the attached data of which option was clicked.

### CODE REVIEW

**Comment by bruh-9000** [comment]
Note that this does require a costume in the sprite using it to function, and the size of said costume is how far away from the arrow the dropdown can be opened from.

**Comment by ego-lay-atman-bay** [comment]
I'm gonna say this now, all the libraries you've been creating PRs for, would probably work better if you just posted them on the forum.

**Comment by bruh-9000** [comment]
@ego-lay-atman-bay Yes, I posted them onto the forum last year, but I don't see a reason not not to add them to the Snap! library now that I found out there is a GitHub.

**Comment by ego-lay-atman-bay** [comment]
I can think of a few reasons that jens may not want to add them. The biggest reason is that the libraries are held on a higher level of quality that also need to fit an actual usecase for. While this dropdown library is good, it's kind of redundant, as there is already a menus library.

**Comment by bruh-9000** [comment]
Hm, I was not aware of the menus library. I will close this PR but I think the other PRs have good use cases.

**Pull request closed without merging**
