### PR TITLE
Rename label to write (manual)

### PR DESCRIPTION
**Pull request by brianharvey**

### CODE REVIEW

**Comment by jmoenig** [comment]
okay, now the filesize again increased by 160% (10.7 MB)?

**Comment by brianharvey** [comment]
Oh, whoops, sorry, I was in too much of a rush to run it through Acrobat.  Stay tuned...

**Comment by brianharvey** [comment]
Aargh this antique (2013 I think) computer won't let me connect to github and upload a file, so it's in
http://cs.berkeley.edu/~bh/SnapManual.pdf

**Comment by jmoenig** [comment]
got your file manually and just added it in https://github.com/jmoenig/Snap/commit/4275b2cfc867afbae0360a6392852450993083f1 closing. Thank you!

**Pull request closed without merging**
