### PR TITLE
Create Ansoboriweriba.xml

### PR DESCRIPTION
**Pull request by TheMapotakes**

### CODE REVIEW

**Comment by jmoenig** [comment]
no explanation, no review

**Comment by TheMapotakes** [comment]
Waaaaaa

**Comment by TheMapotakes** [comment]
Waa waa waa waa waaaaaa

**Comment by TheMapotakes** [comment]
one

**Comment by RubenVerg** [comment]
uuuuuh well this is awkward

**Comment by TheMapotakes** [comment]
Yes

**Comment by programmeruser2** [comment]
Isn't this the same person who spammed on the forums?

**Comment by TheMapotakes** [comment]
Yes

**Pull request closed without merging**
