### PR TITLE
manual and libraries for 6.7

### PR DESCRIPTION
**Pull request by brianharvey**
Several libraries updated.  Manual up to date (including library changes) as of yesterday.  Doesn't talk about duplicating recursive procedure change.

### CODE REVIEW

**Comment by jmoenig** [comment]
excellent, thank you! Will pull tomorrow.

**Review by jmoenig — CHANGES_REQUESTED** [review]
I suck at Github, but it looks like the files for the new manual are missing, or "empty", whatever that mean, both the Word doc and the pdf.

**Comment by brianharvey** [comment]
That's totally weird.  The files are present in the branch I made:
https://github.com/jmoenig/Snap/tree/apl-6-7
so I don't understand how they can be empty in the PR.  And I don't know what to do about it...

**Comment by jmoenig** [comment]
strange. Let me just pull it now and see what happens...

**Comment by jmoenig** [comment]
... and sure enough, both files are there. Okay, thanks and sorry for the confusion. I really suck at Githubbing :-)

**Pull request merged**
