### PR TITLE
minor change because of new user roles

### PR DESCRIPTION
**Pull request by bromagosa**
This is a tiny change that does not affect the editor. We're moving to a more complete user permission system for the social site, where users have roles.

### CODE REVIEW

**Comment by jmoenig** [comment]
sure (great!!). I'll pull it in about an hour. Thanks!

**Comment by brianharvey** [comment]
What's a "user role"?

**Comment by jmoenig** [comment]
I guess something allows for more variety than can be expressed by a Boolean :-)

**Comment by bromagosa** [comment]
Yep. We have admins, moderators, reviewers, regular users and banned users, in order or godness.

**Pull request merged**
