### PR TITLE
Update lang-no.js

### PR DESCRIPTION
**Pull request by brianharvey**
Emailed to me by Olav-Andreas Marschall <olamar@vgs.nfk.no>

I haven't checked it at all.

### CODE REVIEW

**Comment by jmoenig** [comment]
yay, awesome, thanks!

**Comment by olavmars** [comment]
Hi, i submitted the norwegian lang-file in 2013, now I reviewed it and updated it into 2020 6.0 version of Snap. When will this submitted update be included into source files? I have lots of pupils that use the old lang-file with suboptimal norwegian/english interface ?? 
Olav

**Comment by jmoenig** [comment]
Hi Olav, thank you so much for the Norwegian translation update! I've already integrated it into the current dev version that we're about to release within the coming days.

**Comment by olavmars** [comment]
Thanks a lot, Jens, I see forward .... 🙂

________________________________
Fra: Jens Mönig <notifications@github.com>
Sendt: fredag 11. september 2020 20:11
Til: jmoenig/Snap <Snap@noreply.github.com>
Kopi: Olav-Andreas Marschall <olamar@vgs.nfk.no>; Manual <manual@noreply.github.com>
Emne: Re: [jmoenig/Snap] Update lang-no.js (#2680)


Hi Olav, thank you so much for the Norwegian translation update! I've already integrated it into the current dev version that we're about to release within the coming days.

**Pull request merged**
