### PR TITLE
Hyphen

### PR DESCRIPTION
**Pull request by brianharvey**
Fix hyphen in word-sentence.xml

### CODE REVIEW

**Comment by cymplecy** [comment]
Jens - it may be me that's mixed up but I think we need to keep the file needs to be named word-sentence.xml and not sentence.xml

Apologies if its me that's got mixed up :)

**Comment by cymplecy** [comment]
Sorry about rubbish post -edited now :)

**Comment by jmoenig** [comment]
thanks, Simon. I was confused about the alias file which @brianharvey added, and decided to instead rename the actual one. Like to keep the files in a simple, understandable format. It *should* be okay, now, right?

**Comment by cymplecy** [comment]
At this moment in time - the LIBARIES file says word-sentence and the file is called word-sentence so I think we are good :)

I think some housekeeping in dev may be in order to standardize other library names to use dash and not underscore

**Comment by brianharvey** [comment]
I did it that way in the hope of not breaking anyone's still-cached old versions, but I guess that isn't really an issue.

**Comment by jmoenig** [comment]
Thanks, Brian, that explains it!

**Comment by ego-lay-atman-bay** [comment]
Now there's an issue where the words sentances library is a project file instead of a library file.

**Comment by jmoenig** [comment]
Ah, rats! Fixing... Thanks!

**Pull request merged**
