### PR TITLE
Remove shortcut from "shortcut icon"

### LINKED ISSUE #2644: Shortcut is unnecessary inside link
Shortcut is unnecessary inside <code><link rel="shortcut icon" href...></code>. According to MDN, "The shortcut link type is often seen before icon, but this link type is non-conforming, ignored and web authors must not use it anymore."

### PR DESCRIPTION
**Pull request by R4356th**
### Resolves

Resolves #2644.

### Changes

Removes shortcut from <link rel="shortcut icon" href="src/favicon.ico">.

### Cause of Changes

Read #2644.

### CODE REVIEW

**Comment by jmoenig** [comment]
dunno. Who put it in there in the first place, @cycomachead was it you? Any objections to this PR?

**Comment by cycomachead** [comment]
It seems like it was 6 years ago.... hah! This seems fine.

**Comment by jmoenig** [comment]
Thanks, both!

**Comment by cycomachead** [comment]
Yeah apparently sometime the recommendation changed. Interesting. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Pull request merged**
