### PR TITLE
fixes #2402, list utilities library XML was a project one

### LINKED ISSUE #2402: List utilities aren't loading in 5.0
I believe the XML is wrong. It's a  <project>` instead of a `<blocks>`, so it should be easy to fix.

Actually, give me a minute, I can do that.

### PR DESCRIPTION
**Pull request by bromagosa**

### CODE REVIEW

**Comment by jmoenig** [comment]
Thank you, Bernat. @brianharvey , please *test* your stuff before issuing a PR :-)

**Comment by brianharvey** [comment]
Sorry.  I did test it, just not adding it to an existing project in memory.  :(

**Comment by jmoenig** [comment]
Glad @bromagosa discovered it in time, haha. Thanks!

**Comment by bromagosa** [comment]
:+1:

**Pull request merged**
