### PR TITLE
Minor feature: cloud icon changed when user logged in

### PR DESCRIPTION
**Pull request by jathak**
This is in response to #914, implementing the green cloud icon when the user is logged in. @brianharvey   also mentioned changing the icon to red when the cloud is unavailable, but I'm unclear on what specific situations this would include.

### CODE REVIEW

**Comment by khotchkiss13** [comment]
I like it! This is a nice feature that makes it really easy to know your status.

**Comment by jathak** [comment]
Screenshots:

When user is not logged in:
screenshot 2015-09-24 at 1 21 46 pm

When user is logged in:
screenshot 2015-09-24 at 1 22 15 pm

When user is logged in (flat design):
screenshot 2015-09-24 at 1 22 50 pm

**Comment by liam4** [comment]
Oh, I like this! :)

**Comment by jmoenig** [comment]
yeah, I'm not convinced https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/914#issuecomment-143175656

**Pull request closed without merging**
