### PR TITLE
Fix #3038

### LINKED ISSUE #3038: is identical too help has a green `false`
The help for `IS IDENTICAL TO` shows the false case with a green false:

image

Seems like it should show it like this:

image

### PR DESCRIPTION
**Pull request by WarpedWartWars**
@brianharvey is this one good?

### CODE REVIEW

**Review by brianharvey — CHANGES_REQUESTED** [review]
It's great, except that in the bottom part the text "but it's still the same list" is there twice.  :)

**Comment by WarpedWartWars** [comment]
I fixed that bit.

**Review by brianharvey — APPROVED** [review]
Ready to pull, thanks!

**Comment by jmoenig** [comment]
thanks!

**Pull request merged**
