### PR TITLE
Update lang-gl.js

### PR DESCRIPTION
**Pull request by mbouzada**
Galician translation update

### CODE REVIEW

**Comment by jmoenig** [comment]
thank you, @mbouzada ! I'll pull this within the coming days for another maintenance patch coming up...

**Comment by mbouzada** [comment]
I need to correct one small mistake:
Line 2193, error in string closing ( ', ), comma is missing, it should look like this:
        'Marcar para activar\nfuncionalidades de herdanza de obxectos.',

**Comment by jmoenig** [comment]
no problem, @mbouzada , you can simply commit that change to your fork and the PR will become updated automatically as long as I haven't yet pulled it :-)

**Comment by mbouzada** [comment]
I did the pull request by editing the github page, without making a fork in my local

**Comment by bromagosa** [comment]
I fixed that for you, no worries :)

**Comment by jmoenig** [comment]
Thanks, both of you!

**Pull request merged**
