### PR TITLE
Revised Spanish translations

### PR DESCRIPTION
**Pull request by dhmartin**
There were many Spanish translations missing… I merged all messages from "lang-de" and revised a bunch of them, mostly the most visible in the general interface.

### CODE REVIEW

**Comment by jmoenig** [comment]
Thank you so much! I'll pull this and integrate it into the next plannes minor release, probably sometime next week!

**Comment by jmoenig** [comment]
I notice that you're still working on this PR. Do you think it's ready to be pulled or would you prefer for me to wait some more to give you more time? Tnx

**Comment by jmoenig** [comment]
I'm pulling this now. If you have any addenda, please let me know of issue another PR. Thank you!

**Comment by dhmartin** [comment]
It's fine! I did much more than expected and now I'm taking a break on it. I'll provide a new PR when I get back to it.

I saw many strings with recently added new line breaks that seem to have outdated most translations. Is there any reference file with all strings up to date? I read somewhere that it was the German file, but it seems not.

**Pull request merged**
