### PR TITLE
When bignums on, make numeric slots accept +-*/ and i

### PR DESCRIPTION
**Pull request by WarpedWartWars**
Pretty much the title.

BTW @brianharvey told me to make this pull request.

### CODE REVIEW

**Comment by brianharvey** [comment]
(To clarify, he wrote the code on his own initiative, and I suggested he make a PR with it.)

**Comment by WarpedWartWars** [comment]
Yeah.

**Comment by jmoenig** [comment]
Yeah, I hate that library from the bottom of my heart, and the fact that you steadfastly refuse to fix the memory leaks I've been pointing out for months and even years doesn't help.

**Comment by WarpedWartWars** [comment]
> fix the memory leaks

If I know what they are, I might be able to. (Might, as I'm not the best programmer.)

**Comment by WarpedWartWars** [comment]
Closing this so I can make help-screen PRs.

**Comment by brianharvey** [comment]
You can have two different branches open at the same time, you know!

**Comment by WarpedWartWars** [comment]
How? How do I make a second branch?

**Pull request closed without merging**
