### PR TITLE
Updating make-variable library

### PR DESCRIPTION
**Pull request by jguille2**
Hi everyboby,
After some forum discussions and some developers team mails, I think the proposal to update "make-variables" library was clear.

Then, here it is!

To test it and to check translations you can run this project (https://snap.berkeley.edu/snap/snap.html#present:Username=jguille2&ProjectName=TestingMakeVariablesLib)

Please, check Portuguese translation (ping @MMSequeira, of course, I used your words ) and also Deutsch one.

Here I post all the "help info" of these blocks. Then, you (@jmoenig  and @brianharvey )can check that "agreed behavior" and also check my "English description texts"

VarLibHelps

That's all,
Joan

### CODE REVIEW

**Comment by jmoenig** [comment]
this is super cool, @jguille2 ! Will pull within the next days, thank you so much!!

**Comment by MMSequeira** [comment]
I've made some small improvements to the Portuguese translations. I did a pull request for jguille2
/Snap--Build-Your-Own-Blocks (make-variables branch).

**Comment by jguille2** [comment]
Thanks Manuel,
I'll apply your changes, I only wait for other checks. It's weird to track changes on a "1 long line xml file" and, if there are more, I'll send a new PR, trying to contribute with a cleaner commit history.
Thanks again,
Joan

**Comment by jmoenig** [comment]
Hi @jguille2 , please let me know when this is ready to be pulled, then I'll go ahead with it. Thanks!

**Comment by jguille2** [comment]
Ok @jmoenig,

Just a moment to update this with changes reported...
I will notice here.
Joan

**Comment by jguille2** [comment]
Hi @jmoenig,

Just ready to merge. Thanks!
Joan

**Comment by jmoenig** [comment]
Thank you!

**Pull request merged**
