### PR TITLE
Add reportListAttribute.png and sources/help-screen-base.pdn and .png

### PR DESCRIPTION
**Pull request by WarpedWartWars**

### CODE REVIEW

**Review by brianharvey — APPROVED** [review]
Thanks!

**Comment by WarpedWartWars** [comment]
Apparently there's now no need for BLANK and BLANKWIDE, as I added the bases. Should I remove them?

**Comment by brianharvey** [comment]
No, not yet; we still might have other people using other tools while awaiting Jens pulling the translation system.

**Comment by WarpedWartWars** [comment]
Huh?

**Comment by brianharvey** [comment]
Let's not have that conversation on github.  This PR is fine as is, ready to be pulled.

**Pull request merged**
