### PR TITLE
Some additional Greek Translation fixes and updates

### PR DESCRIPTION
**Pull request by HM100**
This fixes some and adds more translation

### CODE REVIEW

**Comment by jmoenig** [comment]
Excellent, thank you! Will pull sometime over the next days.

**Comment by HM100** [comment]
ΟΚ!

**Comment by HM100** [comment]
Good! Only thing is that the updated greek translation while being at this repo, it is not shown while using the program from the snap website (https://snap.berkeley.edu/snap/snap.html)

**Comment by jmoenig** [comment]
that's probably just your browser holding on to a locally cached older version of the translation. It'll either at some time appear or you can flush your browser's cached images and files and then reload Snap!, that should force-update it on your client.

**Comment by HM100** [comment]
> that's probably just your browser holding on to a locally cached older version of the translation. It'll either at some time appear or you can flush your browser's cached images and files and then reload Snap!, that should force-update it on your client.

Did it and worked (On tab for now, others to follow later)

**Pull request merged**
