### PR TITLE
Cleanup documenation

### PR DESCRIPTION
**Pull request by cycomachead**
I'm not sure if the movement of files will be a popular thing, but I think a proper docs folder will be helpful. :)

This PR doesn't change anything about Snap<i>!</i> itself, but it is a start to making development a tiny bit more clear.

Things that I'd like to do:
- Contributing needs to be updated to add instructions on Github, though I think we should still leave the Changeset info in there since it's perfectly valid still. 
- translating needs to reference the Contributing guide since they currently duplicate some info. 
- I'm not sure what to do with the original Readme.txt file, so I just left it there.

The all caps names are for Github. It will link to the contributing file on any pull request to remind anyone of the best practices.

### CODE REVIEW

**Comment by cycomachead** [comment]
Reference:
#613 #425

**Comment by brianharvey** [comment]
Your other two today were no-brainers, but I'm going to wait for Jens to weigh in on this; I suspect it'll break something (e.g., "Download source").

**Comment by cycomachead** [comment]
Yeah, that's fine. (Download Source pulls from the zip file on s.b.e, which is made manually.)

**Comment by brianharvey** [comment]
Yes but in includes some of those doc files (contributing, e.g.) and I bet when you say "manually" you mean "Jens runs a shell script."  :-)

**Comment by brianharvey** [comment]
As I suspected, this one is rejected by Jens, who wants to keep snapsource as flat as possible.

**Comment by cycomachead** [comment]
Ok, I kind of suspected the same thing -- but is there a good reason? The current folder is getting a bit unwieldy... (I recall other issues being posted about similar things). 

However, cleaning / improving the existing documentation would still be useful.  
Would this be pulled if the files were still in their original places?

**Comment by brianharvey** [comment]
If you want to change Contributing, you should discuss the details with Jens by email.  /I'm/ certainly not pulling changes to that!  :-)

**Comment by cycomachead** [comment]
@jmoenig @brianharvey Can we re-visit this, but perhaps keeping things flat, if necessary?

I'll fix the merge conflicts and push a few more tweaks.

**Comment by jmoenig** [comment]
I really, really want to keep things flat, meaning specifically no sub-directories, ideally none at all, because that way I can easily sort everything by whatever I need in different circumstances. What's the problem we're addressing with nested folders?

**Comment by cycomachead** [comment]
> What's the problem we're addressing with nested folders?

Mostly, it gets hard to find what's actually useful, and keeps things organized. (See #197)

However, it's not really super important. It would be good to have better docs and clean up the contributing file.

**Comment by cycomachead** [comment]
@brianharvey @jmoenig 

I undid the docs folder, so now this just has some cleaned up documentation, and then I can work on adding more, but I'll make updating CONTRIBUTING it's own PR.

How does it look now?
See here: https://github.com/cycomachead/snap/tree/docs

**Comment by Klortho** [comment]
:heart: 
Just my 2 cents: I think these changes are big improvements -- especially the list of references to how to get in touch with the community. 

> If you want to change Contributing, you should discuss the details with Jens by email. /I'm/ certainly not pulling changes to that! :-)

You can see the (whitespace suppressed) diff [here](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/pull/690/files?diff=split&w=1#diff-6a3371457528722a734f3c51d9238c13), and there are no substantive changes. Just a little tidying.

**Comment by cycomachead** [comment]
Many of these were recently handled by Jens, there's more I want to do, but I'll handle that later.

**Pull request closed without merging**
