### PR TITLE
Link to go back home

### PR DESCRIPTION
**Pull request by Daniel4-Scratch**
Adds a link to go back home if stuck.
```html
Or go <a href="https://snap.berkeley.edu/">Home</a>
```

### CODE REVIEW

**Comment by jmoenig** [comment]
Can you explain what this PR is about? Thanks!

**Comment by Daniel4-Scratch** [comment]
If, you get stuck on the redirect page, you can go back Home

**Comment by jmoenig** [comment]
why would you get stuck?

**Comment by Daniel4-Scratch** [comment]
Computer errors, stoped loading, just in case. You can close this RP if you want, just and idea

**Comment by jmoenig** [comment]
Okay, thanks. I'll close it for now.

**Pull request closed without merging**
