### PR TITLE
Update stream-tools.xml

### PR DESCRIPTION
**Pull request by brianharvey**
This is the streams library FOR V10 (because it controls the order of blocks in the palette).

### CODE REVIEW

**Comment by jmoenig** [comment]
thanks, Brian. This also should go into v10 dev, right? Can you change the pull request so it doesn't go into the main branch? Thanks!

**Comment by brianharvey** [comment]
Umm, okay, in Github Desktop I said "rebase branch" and it changed it to origin/dev.  But now it's suggesting "force push origin" and I'm afraid to do that because of the "force."  On the github web site it's still based on master.   What do I do now?  (Sorry for being clueless about git...)

**Comment by ego-lay-atman-bay** [comment]
I personally would just create a new branch, and then move your changes to that. Usually a force push means that there are later commits that you would be overriding (getting rid of).

**Comment by brianharvey** [comment]
Okay, done.  It's called dev-streams.  Closing this one.

**Pull request closed without merging**
